name = 'Nhat Dang'
#print(len(name))
#print(name.find('h'))
#print(name.capitalize())
#print(name.upper())
#print(name.lower())
#print(name.isdigit())
#print(name.isalpha())
#print(name.count('a'))
#print(name.replace('a', 'o'))
print(name*3)
